### ISSUE TITLE
Issue with intent: "fraction_detected.geneExpression.across_organs"

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#13]
The nlp is not stable, sometimes it works well but in most cases fails to recognise the following queries:

1) what is the fraction expressing TP53, AHR, MED4, VWF, COL1A1, APOE across organs in human fibroblast? 
it detected the entire question as the features. 
<img width="861" alt="Screen Shot 2023-09-07 at 12 49 32 pm" src="https://github.com/fabilab/cell_atlas_approximations_NLP/assets/98261770/ce6e4809-f0c8-4a38-9295-1634d525bd5a">

2) Compare fraction of cells expressing TP53, APOE, CD19, COL1A1, TGFBI in fibroblast across organs in human. 

It gives a follow up question of: 
You requested average expression across organs: in what cell type?|

**Comment by YingX97** [comment]
But If I changed the word "organs" to "tissues". I can get the plot work.
what is the fraction expressing .... across tissues in human fibroblast?

**Comment by iosonofabio** [comment]
n 2 is fixed 3efb4e8 (0.1.25)

**Comment by iosonofabio** [comment]
both fixed in 0.1.26
