### ISSUE TITLE
Failed to detect intent after replying to follow up question (similar cell types)

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#2]
Hey Fabio, can you please test this question again? 

"show 5 cell types like Lung fibroblast in mouse". 

I gave it a list of genes 'Ptprc,Gzma,Col1a1,Col2a1,Col6a2' to the follow up question, and it replied "Sorry, I didn't get that".

**Comment by iosonofabio** [comment]
It works on my NLP webpack tests, so I cannot reproduce the bug...

**Comment by YingX97** [comment]
Oh, then it's a bug from my end, cheers.
