### ISSUE TITLE
failed to detect celltypes with space

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#20]
Hi Fabio,

Q: "show 10 markers of radial glia in frog brain";
Q: "show 10 markers of AT2 epi in x_laevis brain";
error: "Cell type not found: AT2."

the nlp can only capture the first word of a celltype,

**Comment by iosonofabio** [comment]
this is a tricky one, let me think how to fix it properly.

**Comment by iosonofabio** [comment]
whitelist as of 0.2.10. This might not be the best approach overall, but it works for now and it scales ok-ish to more organisms since multi-word cell types are somewhat rare.
