### ISSUE TITLE
Failed to detect organs

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#21]
Hi Fabio,

I am testing out queries of different organs and celltypes, the some of the followings did not work properly and detected the entire sentence as organ.
Q: "Show the 10 marker genes for urothelial in h_sapiens bladder" ❌
Q: "Show the 10 marker genes for luminal in human mammary" ❌
Q: "Show the 10 marker genes for muller in human eye" ✅ 

here is the api error: 
{
"message": "Organ not found: show 10 markers of urothelial in h_sapiens bladder.",
"error": {
    "type": "invalid_parameter",
    "invalid_parameter": "organ",
    "invalid_value": "show 10 markers of urothelial in h_sapiens bladder"
}
}

**Comment by YingX97** [comment]
Similarly:

Q: What is the expression of TP53, AHR, MED4 in human blood?

api error:
"error": {
    "type": "invalid_parameter",
    "invalid_parameter": "organ",
    "invalid_value": "what is the expression of tp53,ahr,med4 in human blood?"
}

**Comment by iosonofabio** [comment]
all valid bugs, all fixed now in 0.2.7.

Thank you!
