### ISSUE TITLE
Wrong intent when ask for expression across organs

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#25]
Hi Fabio,

Q: "compare expression of APOE, CD19, COL1A1 in **smooth muscle** across tissues in human."

The intent is wrong:  "**_organs.geneExpression_**". However, If I modify the question with a different cell type "**NK**". 

Q: "compare expression of APOE, CD19, COL1A1 in **NK** across tissues in human."

It detected the correct intent "**_average.geneExpression.across_organs_**".

**Comment by iosonofabio** [comment]
fixed in 0.2.25
