### ISSUE TITLE
wrong intent when there is more than 1 space before feature names

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#27]
Hi Fabio,

Q: "Show 10 genes similar to Col1a1 in mouse lung."
Q: "add  Cd19"

when there are 2+ white space before the feature name, the nlp detects the intent as "**zoom.in.neighborhood**". 
In this case, instead of adding the genes, it switched to the neighborhood plot.

Similarly:
Q: "What are the cell states of ML071151a, ML065728a in jellyfish whole?"
Q: "add  ML25764a, ML358828a"
intent: **zoom.in.neighborhood**

**Comment by iosonofabio** [comment]
fixed in 0.2.21
