### ISSUE TITLE
Failed to detect cell types end with ... cells

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#36]
Q: where are **radial glia cells** found across the tree of life?
Q: where are **smooth muscle cells** found across the tree of life?

The nlp detects the cell type as "radial glia cells"
API: https://api.atlasapprox.org/v1/organxorganism?celltype=radial+glia+cells&measurement_type=gene_expression

**Comment by iosonofabio** [comment]
thank you, fixed in 0.2.33

**Comment by iosonofabio** [comment]
PS: already deployed
