### ISSUE TITLE
add a new intent 'Explore organism'

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#5]
Maybe we can add an ‘explore’ intent. When user type in query such as ‘Explore Human’. It show a list of command related to this specific organism on the left side, 

- We can show them a complete profile of that species on the right side
    - photo
    - What organs
    - What kind of measurement (gene expression, chromatin accessibility, etc)
    - what cell types are available
- Make the page scrollable

**Comment by iosonofabio** [comment]
Intent added and tested. It works. Closing.

@YingX97 : you might want to open an issue on the HI repo with those details.
