### ISSUE TITLE
Only the first gene is detected when genes are separated by ",   "

### ISSUE THREAD

**Issue by YingX97** [fabilab/cell_atlas_approximations_NLP#8]
When submitting a query with multiple genes separated by a comma followed by a space (", "), the system only recognizes the first gene in the list.
**Question**: What is the average expression of Col1a1, Col1a2, Adh1, Tgfbi, Crh, Cd19 in mouse lung?
**Bot's reply**: The average expression of Col1a1 in m_musculus Lung is shown in the plot.|

**Comment by iosonofabio** [comment]
Fixed in 0.1.16.
